### ISSUE TITLE
`Local IDE sync` mis-updated for Codenvy

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy-docs#30]
The following page: https://codenvy.com/docs/user-guide/sync/index.html

Is having issues:
- image not rendered
- content not adapted to codenvy

**Comment by riuvshin** [comment]
@bmicklea @JamesDrummond who is on this? do wee need this for 5.2.0 ?

**Comment by bmicklea** [comment]
I think @JamesDrummond may have taken care of this already...if not then it
should be for 5.2

> --

Brad Micklea | Codenvy | bmicklea@​codenvy.​com | 4​16​.7​07​.07​92

**Comment by JamesDrummond** [comment]
Taken care of https://github.com/eclipse/che-docs/blob/master/src/main/_docs/workspace-administration/ws-volume-mounts.md .
