### ISSUE TITLE
Auditing capabilities are not documented

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy-docs#34]
The work from this issue is not documented:
https://github.com/codenvy/codenvy/issues/581

**Comment by slemeur** [comment]
@dmytro-ndp Could you help us on this issue please?

**Comment by dmytro-ndp** [comment]
@slemeur: I am on vocation now untill next week. Meanwhile you could use next info to write documentation:
1. Url of audit service: \<Codenvy host url>/api/audit
1. Response of GET request to audit service - text file named **<date-time>.txt** with content like the follow: https://github.com/codenvy/codenvy/issues/1437#issuecomment-271988752

**Comment by bmicklea** [comment]
PR created: https://github.com/codenvy/codenvy-docs/pull/35

**Comment by riuvshin** [comment]
@bmicklea  pr is merged should we close this  /
